### Midterm Exam
#                                               Aritificial Intelligence 

In [42]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import scipy.stats as stats
import plotly.express as px
import networkx as nx

In [43]:
def bfs_with_distance(adj_list, start, num_vertices):
    #create a list of all the vertices
    vertices = [i for i in range(num_vertices)]
    distances = {i:float('inf') for i in vertices}
    distances[start] = 0
    queue = [start]
    order_visited = []
    while queue:
        #pop the first element in the queue
        current = queue.pop(0)
        #add the current vertex to the order visited
        order_visited.append(current)
        #for each neighbor of the current vertex
        for neighbor in adj_list[current]:
            if distances[neighbor] == float('inf'):
                distances[neighbor] = distances[current] + 1
                queue.append(neighbor)
    return order_visited, list(distances.values())


In [44]:
# Example graph:
# 0 -> 1 -> 2
# |    |    |
# v    v    v
# 3 -> 4 <- 5
adj_list = [
    [1, 3],
    [2, 4],
    [5],
    [4],
    [],
    [4]
]

# Test case 1:
start = 0
num_vertices = 6
order_visited, distances = bfs_with_distance(adj_list, start, num_vertices)
print(order_visited)
#visualize_path(order_visited, distances)

# Test case 2:
start = 3
num_vertices = 6
order_visited, distances = bfs_with_distance(adj_list, start, num_vertices)

print(order_visited)
# Test case 3:
start = 5
num_vertices = 6
order_visited, distances = bfs_with_distance(adj_list, start, num_vertices)
print(order_visited)


print("All test cases passed!")


[0, 1, 3, 2, 4, 5]
[3, 4]
[5, 4]
All test cases passed!


### Question number 2

In [45]:
#write a function to read the cube from a text file
def read_file(filename):
    # open the file
    with open(filename) as file:
        # read the lines
        lines = file.readlines()
        # create an empty list to store the lines
        lines_list = []
        # for each line
        for line in lines:
            # remove the new line character
            line = line.strip()
            # split the line
            line = line.split()
            # convert the line to a list of integers
            line = [int(i) for i in line]
            # append the line to the list
            lines_list.append(line)
        # convert the list to a numpy array
        cube = np.array(lines_list)
    # return the cube
    return cube

file = 'graph.txt'
cube = read_file(file)
print(cube)


[[6 0 0 0 0 0 0 0 0 1]
 [1 1 0 1 0 1 1 1 1 1]
 [0 1 0 1 0 0 0 0 0 1]
 [1 1 0 1 0 1 1 1 0 1]
 [0 1 0 1 0 0 0 1 0 0]
 [0 1 2 0 0 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 0 1 1 1 0 1]
 [0 0 0 0 0 1 0 0 0 1]
 [0 1 1 1 1 1 0 1 0 7]]


### Following is the simple implementation of the A* algorithm

In [46]:
def A_star(cube):
    dim = cube.shape[0]
    start = np.where(cube == 6)
    goal = np.where(cube == 7)
    queue = []
    visited = []
    heappush(queue, (0, 0, start))
    while queue:
        node = heappop(queue)
        # if the node is not visited
        if node[2] not in visited:
            # mark the node as visited
            visited.append(node[2])
            # if the node is the goal point
            if cube[node[2]] == 7:
                # return the path
                return visited
            # get the neighbors of the node
            neighbors = get_neighbors(node[2], dim)
            # for each neighbor
            for neighbor in neighbors:
                # if the neighbor is not a wall
                if cube[neighbor] != 1:
                    heappush(queue, (node[1] + 1 + euclidean_distance(neighbor, goal), node[1] + 1, neighbor))
    
    # if there is no path from the start point to the goal point
    return -1


def euclidean_distance(point1, point2):
    row1 = point1[0]
    col1 = point1[1]
    row2 = point2[0]
    col2 = point2[1]
    distance = np.sqrt((row1 - row2) ** 2 + (col1 - col2) ** 2)
    return distance

#write heappush and heappop functions
def heappush(heap, item):
    heap.append(item)
    _siftdown(heap, 0, len(heap)-1)

def heappop(heap):
    lastelt = heap.pop()    # raises appropriate IndexError if heap is empty
    if heap:
        returnitem = heap[0]
        heap[0] = lastelt
        _siftup(heap, 0)
        return returnitem
    return lastelt

def _siftdown(heap, startpos, pos):
    newitem = heap[pos]
    while pos > startpos:
        parentpos = (pos - 1) >> 1
        parent = heap[parentpos]
        if newitem < parent:
            heap[pos] = parent
            pos = parentpos
            continue
        break
    heap[pos] = newitem
    
    
def _siftup(heap, pos):
    endpos = len(heap)
    startpos = pos
    newitem = heap[pos]
    # Bubble up the smaller child until hitting a leaf.
    childpos = 2*pos + 1    # leftmost child position
    while childpos < endpos:
        # Set childpos to index of smaller child.
        rightpos = childpos + 1
        if rightpos < endpos and not heap[childpos] < heap[rightpos]:
            childpos = rightpos
        # Move the smaller child up.
        heap[pos] = heap[childpos]
        pos = childpos
        childpos = 2*pos + 1
    heap[pos] = newitem
    _siftdown(heap, startpos, pos)